use crate::characteristics::Characteristic;
use crate::errors::Error;
use crate::positions::{Position, PositionDefinition};
use crate::rosters::Roster;
use crate::skills::{Skill, SkillCategory};
use std::collections::HashMap;

fn star_player_default_definition(cost: u32) -> PositionDefinition {
    PositionDefinition {
        maximum_quantity: 1,
        cost,
        characteristics: Default::default(),
        skills: vec![],
        primary_skill_categories: vec![],
        secondary_skill_categories: vec![],
        is_big_man: false,
    }
}

pub fn positon_definition_from(
    roster: Roster,
    position: Position,
) -> Result<PositionDefinition, Error> {
    match (roster, position) {
        //*************************************************************************************
        // Amazon
        //*************************************************************************************
        (Roster::Amazon, Position::EagleWarriorLinewoman) => Ok(PositionDefinition {
            maximum_quantity: 16,
            cost: 50000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Dodge],
            primary_skill_categories: vec![SkillCategory::General],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Amazon, Position::PythonWarriorThrower) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 80000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 3),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Dodge, Skill::OnTheBall, Skill::Pass, Skill::SafePass],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Pass],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Amazon, Position::PiranhaWarriorBlitzer) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 90000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Dodge, Skill::HitAndRun, Skill::JumpUp],
            primary_skill_categories: vec![SkillCategory::Agility, SkillCategory::General],
            secondary_skill_categories: vec![SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Amazon, Position::JaguarWarriorBlocker) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 110000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 4),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::Defensive, Skill::Dodge],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),

        //*************************************************************************************
        // Chaos Chosen
        //*************************************************************************************
        (Roster::ChaosChosen, Position::BeastmanRunnerLineman) => Ok(PositionDefinition {
            maximum_quantity: 16,
            cost: 60000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::Horns],
            primary_skill_categories: vec![
                SkillCategory::General,
                SkillCategory::Mutation,
                SkillCategory::Strength,
            ],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::ChaosChosen, Position::ChosenBlocker) => Ok(PositionDefinition {
            maximum_quantity: 4,
            cost: 100000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 4),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![],
            primary_skill_categories: vec![
                SkillCategory::General,
                SkillCategory::Mutation,
                SkillCategory::Strength,
            ],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::ChaosChosen, Position::ChaosTroll) => Ok(PositionDefinition {
            maximum_quantity: 1,
            cost: 115000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 4),
                (Characteristic::Strength, 5),
                (Characteristic::Agility, 5),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![
                Skill::AlwaysHungry,
                Skill::Loner(4),
                Skill::MightyBlow(1),
                Skill::ProjectileVomit,
                Skill::ReallyStupid,
                Skill::Regeneration,
                Skill::ThrowTeamMate,
            ],
            primary_skill_categories: vec![SkillCategory::Mutation, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::General],
            is_big_man: true,
        }),
        (Roster::ChaosChosen, Position::ChaosOgre) => Ok(PositionDefinition {
            maximum_quantity: 1,
            cost: 140000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 5),
                (Characteristic::Agility, 4),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![
                Skill::BoneHead,
                Skill::Loner(4),
                Skill::MightyBlow(1),
                Skill::ThickSkull,
                Skill::ThrowTeamMate,
            ],
            primary_skill_categories: vec![SkillCategory::Mutation, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::General],
            is_big_man: true,
        }),
        (Roster::ChaosChosen, Position::Minotaur) => Ok(PositionDefinition {
            maximum_quantity: 1,
            cost: 150000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 5),
                (Characteristic::Agility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![
                Skill::Frenzy,
                Skill::Horns,
                Skill::Loner(4),
                Skill::MightyBlow(1),
                Skill::ThickSkull,
                Skill::UnchannelledFury,
            ],
            primary_skill_categories: vec![SkillCategory::Mutation, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::General],
            is_big_man: true,
        }),

        //*************************************************************************************
        // Dark Elf
        //*************************************************************************************
        (Roster::DarkElf, Position::DarkElfLineman) => Ok(PositionDefinition {
            maximum_quantity: 12,
            cost: 70000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::DarkElf, Position::Runner) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 80000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 3),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::DumpOff],
            primary_skill_categories: vec![
                SkillCategory::General,
                SkillCategory::Agility,
                SkillCategory::Pass,
            ],
            secondary_skill_categories: vec![SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::DarkElf, Position::Blitzer) => Ok(PositionDefinition {
            maximum_quantity: 4,
            cost: 100000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::Block],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::DarkElf, Position::Assassin) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 85000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Shadowing, Skill::Stab],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::DarkElf, Position::WitchElf) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 110000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Dodge, Skill::Frenzy, Skill::JumpUp],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),

        //*************************************************************************************
        // Dwarf
        //*************************************************************************************
        (Roster::Dwarf, Position::DwarfBlockerLineman) => Ok(PositionDefinition {
            maximum_quantity: 12,
            cost: 70000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 4),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 4),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![Skill::Block, Skill::Tackle, Skill::ThickSkull],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::Dwarf, Position::Runner) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 85000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::SureHands, Skill::ThickSkull],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Pass],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Dwarf, Position::Blitzer) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 80000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![Skill::Block, Skill::ThickSkull],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::Dwarf, Position::TrollSlayer) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 95000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![
                Skill::Block,
                Skill::Dauntless,
                Skill::Frenzy,
                Skill::ThickSkull,
            ],
            primary_skill_categories: vec![SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::General],
            is_big_man: false,
        }),
        (Roster::Dwarf, Position::Deathroller) => Ok(PositionDefinition {
            maximum_quantity: 1,
            cost: 170000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 4),
                (Characteristic::Strength, 7),
                (Characteristic::Agility, 5),
                (Characteristic::ArmourValue, 11),
            ]),
            skills: vec![
                Skill::BreakTackle,
                Skill::DirtyPlayer(2),
                Skill::Juggernaut,
                Skill::Loner(5),
                Skill::MightyBlow(1),
                Skill::NoHands,
                Skill::SecretWeapon,
                Skill::StandFirm,
            ],
            primary_skill_categories: vec![SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::General],
            is_big_man: true,
        }),

        //*************************************************************************************
        // Gnome
        //*************************************************************************************
        (Roster::Gnome, Position::GnomeLineman) => Ok(PositionDefinition {
            maximum_quantity: 16,
            cost: 40000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 7),
            ]),
            skills: vec![
                Skill::JumpUp,
                Skill::RightStuff,
                Skill::Stunty,
                Skill::Wrestle,
            ],
            primary_skill_categories: vec![SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Gnome, Position::GnomeBeastmaster) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 55000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Guard, Skill::JumpUp, Skill::Stunty, Skill::Wrestle],
            primary_skill_categories: vec![SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Gnome, Position::GnomeIllusionist) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 50000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 3),
                (Characteristic::ArmourValue, 7),
            ]),
            skills: vec![
                Skill::JumpUp,
                Skill::Stunty,
                Skill::Trickster,
                Skill::Wrestle,
            ],
            primary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Pass],
            secondary_skill_categories: vec![SkillCategory::General],
            is_big_man: false,
        }),
        (Roster::Gnome, Position::WoodlandFox) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 50000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 2),
                (Characteristic::ArmourValue, 6),
            ]),
            skills: vec![Skill::Dodge, Skill::MyBall, Skill::SideStep, Skill::Stunty],
            primary_skill_categories: vec![],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::Gnome, Position::AlternForestTreeman) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 120000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 2),
                (Characteristic::Strength, 6),
                (Characteristic::Agility, 5),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 11),
            ]),
            skills: vec![
                Skill::MightyBlow(1),
                Skill::StandFirm,
                Skill::StrongArm,
                Skill::TakeRoots,
                Skill::ThickSkull,
                Skill::ThrowTeamMate,
                Skill::Timmmber,
            ],
            primary_skill_categories: vec![SkillCategory::Strength],
            secondary_skill_categories: vec![
                SkillCategory::Agility,
                SkillCategory::General,
                SkillCategory::Pass,
            ],
            is_big_man: true,
        }),

        //*************************************************************************************
        // High Elf
        //*************************************************************************************
        (Roster::HighElf, Position::Lineman) => Ok(PositionDefinition {
            maximum_quantity: 16,
            cost: 70000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::HighElf, Position::Catcher) => Ok(PositionDefinition {
            maximum_quantity: 4,
            cost: 90000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 8),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Catch],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::HighElf, Position::Thrower) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 100000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 2),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::CloudBurster, Skill::Pass, Skill::SafePass],
            primary_skill_categories: vec![
                SkillCategory::General,
                SkillCategory::Agility,
                SkillCategory::Pass,
            ],
            secondary_skill_categories: vec![SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::HighElf, Position::Blitzer) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 100000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::Block],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),

        //*************************************************************************************
        // Human
        //*************************************************************************************
        (Roster::Human, Position::HumanLineman) => Ok(PositionDefinition {
            maximum_quantity: 16,
            cost: 50000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![],
            primary_skill_categories: vec![SkillCategory::General],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::Human, Position::Thrower) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 80000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 2),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::Pass, Skill::SureHands],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Pass],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::Human, Position::Catcher) => Ok(PositionDefinition {
            maximum_quantity: 4,
            cost: 65000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 8),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Catch, Skill::Dodge],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::Human, Position::Blitzer) => Ok(PositionDefinition {
            maximum_quantity: 4,
            cost: 85000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::Block],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::Human, Position::HalflingHopeful) => Ok(PositionDefinition {
            maximum_quantity: 3,
            cost: 30000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 7),
            ]),
            skills: vec![Skill::Dodge, Skill::RightStuff, Skill::Stunty],
            primary_skill_categories: vec![SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Human, Position::Ogre) => Ok(PositionDefinition {
            maximum_quantity: 1,
            cost: 140000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 5),
                (Characteristic::Agility, 4),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![
                Skill::BoneHead,
                Skill::Loner(4),
                Skill::MightyBlow(1),
                Skill::ThickSkull,
                Skill::ThrowTeamMate,
            ],
            primary_skill_categories: vec![SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            is_big_man: true,
        }),

        //*************************************************************************************
        // Lizardmen
        //*************************************************************************************
        (Roster::Lizardmen, Position::SkinkRunnerLineman) => Ok(PositionDefinition {
            maximum_quantity: 12,
            cost: 60000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 8),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Dodge, Skill::Stunty],
            primary_skill_categories: vec![SkillCategory::Agility],
            secondary_skill_categories: vec![
                SkillCategory::General,
                SkillCategory::Pass,
                SkillCategory::Strength,
            ],
            is_big_man: false,
        }),
        (Roster::Lizardmen, Position::ChameleonSkink) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 70000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 3),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![
                Skill::Dodge,
                Skill::OnTheBall,
                Skill::Shadowing,
                Skill::Stunty,
            ],
            primary_skill_categories: vec![SkillCategory::Agility],
            secondary_skill_categories: vec![
                SkillCategory::General,
                SkillCategory::Pass,
                SkillCategory::Strength,
            ],
            is_big_man: false,
        }),
        (Roster::Lizardmen, Position::SaurusBlocker) => Ok(PositionDefinition {
            maximum_quantity: 6,
            cost: 85000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 4),
                (Characteristic::Agility, 5),
                (Characteristic::PassingAbility, 6),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::Lizardmen, Position::Kroxigor) => Ok(PositionDefinition {
            maximum_quantity: 1,
            cost: 140000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 5),
                (Characteristic::Agility, 5),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![
                Skill::BoneHead,
                Skill::Loner(4),
                Skill::MightyBlow(1),
                Skill::PrehensileTail,
                Skill::ThickSkull,
            ],
            primary_skill_categories: vec![SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            is_big_man: true,
        }),

        //*************************************************************************************
        // NecromanticHorror
        //*************************************************************************************
        (Roster::NecromanticHorror, Position::ZombieLineman) => Ok(PositionDefinition {
            maximum_quantity: 16,
            cost: 40000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 4),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::Regeneration],
            primary_skill_categories: vec![SkillCategory::General],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::NecromanticHorror, Position::GhoulRunner) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 75000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Dodge],
            primary_skill_categories: vec![SkillCategory::Agility, SkillCategory::General],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::NecromanticHorror, Position::Wraith) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 95000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![
                Skill::Block,
                Skill::FoulAppearance,
                Skill::NoHands,
                Skill::Regeneration,
                Skill::SideStep,
            ],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::NecromanticHorror, Position::Werewolf) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 125000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 8),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::Claws, Skill::Frenzy, Skill::Regeneration],
            primary_skill_categories: vec![SkillCategory::Agility, SkillCategory::General],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::NecromanticHorror, Position::FleshGolem) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 115000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 4),
                (Characteristic::Strength, 4),
                (Characteristic::Agility, 4),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![Skill::Regeneration, Skill::StandFirm, Skill::ThickSkull],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),

        //*************************************************************************************
        // Norse
        //*************************************************************************************
        (Roster::Norse, Position::NorseRaiderLineman) => Ok(PositionDefinition {
            maximum_quantity: 16,
            cost: 50000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Block, Skill::Drunkard, Skill::ThickSkull],
            primary_skill_categories: vec![SkillCategory::General],
            secondary_skill_categories: vec![
                SkillCategory::Agility,
                SkillCategory::Pass,
                SkillCategory::Strength,
            ],
            is_big_man: false,
        }),
        (Roster::Norse, Position::BeerBoar) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 20000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 1),
                (Characteristic::Agility, 3),
                (Characteristic::ArmourValue, 6),
            ]),
            skills: vec![
                Skill::Dodge,
                Skill::NoHands,
                Skill::PickMeUp,
                Skill::Stunty,
                Skill::Titchy,
            ],
            primary_skill_categories: vec![],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::Norse, Position::NorseBerzerker) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 90000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Block, Skill::Frenzy, Skill::JumpUp],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::Norse, Position::Valkyrie) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 95000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 3),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![
                Skill::Catch,
                Skill::Dauntless,
                Skill::Pass,
                Skill::StripBall,
            ],
            primary_skill_categories: vec![
                SkillCategory::Agility,
                SkillCategory::General,
                SkillCategory::Pass,
            ],
            secondary_skill_categories: vec![SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Norse, Position::Ulfwerener) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 105000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 4),
                (Characteristic::Agility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![Skill::Frenzy],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::Norse, Position::Yhetee) => Ok(PositionDefinition {
            maximum_quantity: 1,
            cost: 140000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 5),
                (Characteristic::Agility, 4),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![
                Skill::Claws,
                Skill::DisturbingPresence,
                Skill::Frenzy,
                Skill::Loner(4),
                Skill::UnchannelledFury,
            ],
            primary_skill_categories: vec![SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            is_big_man: true,
        }),

        //*************************************************************************************
        // Orc
        //*************************************************************************************
        (Roster::Orc, Position::OrcLineman) => Ok(PositionDefinition {
            maximum_quantity: 16,
            cost: 50000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![Skill::Animosity(Position::OrcLineman)],
            primary_skill_categories: vec![SkillCategory::General],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Orc, Position::Thrower) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 65000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 3),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![
                Skill::Animosity(Position::All),
                Skill::Pass,
                Skill::SureHands,
            ],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Pass],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Orc, Position::Blitzer) => Ok(PositionDefinition {
            maximum_quantity: 4,
            cost: 80000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![Skill::Animosity(Position::All), Skill::Block],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::Orc, Position::BigUn) => Ok(PositionDefinition {
            maximum_quantity: 4,
            cost: 90000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 4),
                (Characteristic::Agility, 4),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![Skill::Animosity(Position::BigUn)],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility],
            is_big_man: false,
        }),
        (Roster::Orc, Position::Goblin) => Ok(PositionDefinition {
            maximum_quantity: 4,
            cost: 40000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Dodge, Skill::RightStuff, Skill::Stunty],
            primary_skill_categories: vec![SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::General, SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::Orc, Position::UntrainedTroll) => Ok(PositionDefinition {
            maximum_quantity: 1,
            cost: 115000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 4),
                (Characteristic::Strength, 5),
                (Characteristic::Agility, 5),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![
                Skill::AlwaysHungry,
                Skill::Loner(4),
                Skill::MightyBlow(1),
                Skill::ProjectileVomit,
                Skill::ReallyStupid,
                Skill::Regeneration,
                Skill::ThrowTeamMate,
            ],
            primary_skill_categories: vec![SkillCategory::Strength],
            secondary_skill_categories: vec![
                SkillCategory::Agility,
                SkillCategory::General,
                SkillCategory::Pass,
            ],
            is_big_man: true,
        }),

        //*************************************************************************************
        // Snotling
        //*************************************************************************************
        (Roster::Snotling, Position::SnotlingLineman) => Ok(PositionDefinition {
            maximum_quantity: 16,
            cost: 15000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 1),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 6),
            ]),
            skills: vec![
                Skill::Dodge,
                Skill::RightStuff,
                Skill::SideStep,
                Skill::Stunty,
                Skill::Swarming,
                Skill::Titchy,
            ],
            primary_skill_categories: vec![SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::General],
            is_big_man: false,
        }),
        (Roster::Snotling, Position::FungusFlinga) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 30000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 5),
                (Characteristic::Strength, 1),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 6),
            ]),
            skills: vec![
                Skill::Bombardier,
                Skill::Dodge,
                Skill::RightStuff,
                Skill::SecretWeapon,
                Skill::SideStep,
                Skill::Stunty,
            ],
            primary_skill_categories: vec![SkillCategory::Agility, SkillCategory::Pass],
            secondary_skill_categories: vec![SkillCategory::General],
            is_big_man: false,
        }),
        (Roster::Snotling, Position::FunHoppa) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 20000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 1),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 6),
            ]),
            skills: vec![
                Skill::Dodge,
                Skill::PogoStick,
                Skill::RightStuff,
                Skill::SideStep,
                Skill::Stunty,
            ],
            primary_skill_categories: vec![SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::General],
            is_big_man: false,
        }),
        (Roster::Snotling, Position::StiltyRunna) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 20000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 6),
                (Characteristic::Strength, 1),
                (Characteristic::Agility, 3),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 6),
            ]),
            skills: vec![
                Skill::Dodge,
                Skill::RightStuff,
                Skill::SideStep,
                Skill::Sprint,
                Skill::Stunty,
            ],
            primary_skill_categories: vec![SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::General],
            is_big_man: false,
        }),
        (Roster::Snotling, Position::PumpWagon) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 105000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 4),
                (Characteristic::Strength, 5),
                (Characteristic::Agility, 5),
                (Characteristic::ArmourValue, 9),
            ]),
            skills: vec![
                Skill::DirtyPlayer(1),
                Skill::Juggernaut,
                Skill::MightyBlow(1),
                Skill::ReallyStupid,
                Skill::SecretWeapon,
                Skill::StandFirm,
            ],
            primary_skill_categories: vec![SkillCategory::Strength],
            secondary_skill_categories: vec![SkillCategory::Agility, SkillCategory::General],
            is_big_man: true,
        }),
        (Roster::Snotling, Position::TrainedTroll) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 115000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 4),
                (Characteristic::Strength, 5),
                (Characteristic::Agility, 5),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 10),
            ]),
            skills: vec![
                Skill::AlwaysHungry,
                Skill::Loner(3),
                Skill::MightyBlow(1),
                Skill::ProjectileVomit,
                Skill::ReallyStupid,
                Skill::Regeneration,
                Skill::ThrowTeamMate,
            ],
            primary_skill_categories: vec![SkillCategory::Strength],
            secondary_skill_categories: vec![
                SkillCategory::Agility,
                SkillCategory::General,
                SkillCategory::Pass,
            ],
            is_big_man: true,
        }),

        //*************************************************************************************
        // Wood ELf
        //*************************************************************************************
        (Roster::WoodElf, Position::WoodElfLineman) => Ok(PositionDefinition {
            maximum_quantity: 12,
            cost: 70000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::WoodElf, Position::Thrower) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 95000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 7),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 2),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Pass],
            primary_skill_categories: vec![
                SkillCategory::General,
                SkillCategory::Agility,
                SkillCategory::Pass,
            ],
            secondary_skill_categories: vec![SkillCategory::Strength],
            is_big_man: false,
        }),
        (Roster::WoodElf, Position::Catcher) => Ok(PositionDefinition {
            maximum_quantity: 4,
            cost: 90000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 8),
                (Characteristic::Strength, 2),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Catch, Skill::Dodge],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::WoodElf, Position::Wardancer) => Ok(PositionDefinition {
            maximum_quantity: 2,
            cost: 125000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 8),
                (Characteristic::Strength, 3),
                (Characteristic::Agility, 2),
                (Characteristic::PassingAbility, 4),
                (Characteristic::ArmourValue, 8),
            ]),
            skills: vec![Skill::Block, Skill::Dodge, Skill::Leap],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength, SkillCategory::Pass],
            is_big_man: false,
        }),
        (Roster::WoodElf, Position::LorenForestTreeman) => Ok(PositionDefinition {
            maximum_quantity: 1,
            cost: 120000,
            characteristics: HashMap::from([
                (Characteristic::MovementAllowance, 2),
                (Characteristic::Strength, 6),
                (Characteristic::Agility, 5),
                (Characteristic::PassingAbility, 5),
                (Characteristic::ArmourValue, 11),
            ]),
            skills: vec![
                Skill::Loner(4),
                Skill::MightyBlow(1),
                Skill::StandFirm,
                Skill::StrongArm,
                Skill::TakeRoots,
                Skill::ThickSkull,
                Skill::ThrowTeamMate,
            ],
            primary_skill_categories: vec![SkillCategory::General, SkillCategory::Agility],
            secondary_skill_categories: vec![SkillCategory::Strength],
            is_big_man: true,
        }),

        //*************************************************************************************
        // Stars
        //*************************************************************************************
        (_, Position::AkhorneTheSquirrel) => Ok(star_player_default_definition(80000)),
        (_, Position::AnqiPanqi) => Ok(star_player_default_definition(190000)),
        (_, Position::BarikFarblast) => Ok(star_player_default_definition(80000)),
        (_, Position::BilerotVomitflesh) => Ok(star_player_default_definition(180000)),
        (_, Position::BoaKonSsstriktr) => Ok(star_player_default_definition(200000)),
        (_, Position::BryceTheSliceCambuel) => Ok(star_player_default_definition(130000)),
        (_, Position::CaptainKarinaVonRiesz) => Ok(star_player_default_definition(230000)),
        (_, Position::CountLuthorVonDrakenborg) => Ok(star_player_default_definition(340000)),
        (_, Position::DriblAndDrull) => Ok(star_player_default_definition(190000)),
        (_, Position::EldrilSidewinder) => Ok(star_player_default_definition(230000)),
        (_, Position::EstelleLaVeneaux) => Ok(star_player_default_definition(190000)),
        (_, Position::FrankNStein) => Ok(star_player_default_definition(250000)),
        (_, Position::FungusTheLoon) => Ok(star_player_default_definition(80000)),
        (_, Position::GlartSmashrip) => Ok(star_player_default_definition(195000)),
        (_, Position::GlorielSummerbloom) => Ok(star_player_default_definition(150000)),
        (_, Position::GlotlStop) => Ok(star_player_default_definition(270000)),
        (_, Position::GrakAndCrumbleberry) => Ok(star_player_default_definition(250000)),
        (_, Position::GrashnakBlackhoof) => Ok(star_player_default_definition(240000)),
        (_, Position::GretchenWachterTheBloodBowlWidow) => {
            Ok(star_player_default_definition(260000))
        }
        (_, Position::GrimIronjaw) => Ok(star_player_default_definition(200000)),
        (_, Position::GrombrindalTheWhiteDwarf) => Ok(star_player_default_definition(210000)),
        (_, Position::GufflePussmaw) => Ok(star_player_default_definition(180000)),
        (_, Position::HelmutWulf) => Ok(star_player_default_definition(140000)),
        (_, Position::HTharkTheUnstoppable) => Ok(star_player_default_definition(300000)),
        (_, Position::IvanTAnimalDeathshroud) => Ok(star_player_default_definition(190000)),
        (_, Position::IvarEriksson) => Ok(star_player_default_definition(245000)),
        (_, Position::JeremiahKool) => Ok(star_player_default_definition(320000)),
        (_, Position::JordellFreshbreeze) => Ok(star_player_default_definition(250000)),
        (_, Position::KarlaVonKill) => Ok(star_player_default_definition(210000)),
        (_, Position::KirothKrakeneye) => Ok(star_player_default_definition(160000)),
        (_, Position::LordBorakTheDespoiler) => Ok(star_player_default_definition(260000)),
        (_, Position::MapleHighgrove) => Ok(star_player_default_definition(210000)),
        (_, Position::MaxSpleenripper) => Ok(star_player_default_definition(130000)),
        (_, Position::MightyZug) => Ok(star_player_default_definition(220000)),
        (_, Position::NobblaBlackwart) => Ok(star_player_default_definition(120000)),
        (_, Position::PuggyBaconbreath) => Ok(star_player_default_definition(120000)),
        (_, Position::RashnakBackstabber) => Ok(star_player_default_definition(130000)),
        (_, Position::RipperBolgrot) => Ok(star_player_default_definition(250000)),
        (_, Position::RodneyRoachbait) => Ok(star_player_default_definition(70000)),
        (_, Position::RowanaForestfoot) => Ok(star_player_default_definition(160000)),
        (_, Position::RoxannaDarknail) => Ok(star_player_default_definition(270000)),
        (_, Position::RumbelowSheepskin) => Ok(star_player_default_definition(170000)),
        (_, Position::ScrappaSorehead) => Ok(star_player_default_definition(130000)),
        (_, Position::ScylaAnfingrimm) => Ok(star_player_default_definition(200000)),
        (_, Position::SkitterStabStab) => Ok(star_player_default_definition(150000)),
        (_, Position::SkrorgSnowpelt) => Ok(star_player_default_definition(250000)),
        (_, Position::SkrullHalfheight) => Ok(star_player_default_definition(150000)),
        (_, Position::SwiftvineGlimmershard) => Ok(star_player_default_definition(110000)),
        (_, Position::TheBlackGobbo) => Ok(star_player_default_definition(225000)),
        (_, Position::TheSwiftTwins) => Ok(star_player_default_definition(340000)),
        (_, Position::ThorssonStoutmead) => Ok(star_player_default_definition(170000)),
        (_, Position::VaragGhoulChewer) => Ok(star_player_default_definition(280000)),
        (_, Position::WilhelmChaney) => Ok(star_player_default_definition(220000)),
        (_, Position::WillowRosebark) => Ok(star_player_default_definition(150000)),
        (_, Position::WithergraspDoubledrool) => Ok(star_player_default_definition(170000)),
        (_, Position::ZolcathTheZoat) => Ok(star_player_default_definition(230000)),
        (_, Position::ZzhargMadeye) => Ok(star_player_default_definition(130000)),
        (_, Position::BomberDribblesnot) => Ok(star_player_default_definition(50000)),
        (_, Position::CindyPiewhistle) => Ok(star_player_default_definition(50000)),
        (_, Position::DeeprootStrongbranch) => Ok(star_player_default_definition(280000)),
        (_, Position::GriffOberwald) => Ok(star_player_default_definition(280000)),
        (_, Position::HakflemSkuttlespike) => Ok(star_player_default_definition(210000)),
        (_, Position::KreekTheVerminatorRustgouger) => Ok(star_player_default_definition(170000)),
        (_, Position::MorgNThorg) => Ok(star_player_default_definition(380000)),

        // Others
        _ => Err(Error::PositionNotDefined),
    }
}
