use crate::positions::Position;
use crate::rosters::{
    DedicatedFansInformation, Roster, RosterDefinition, SpecialRule, StaffInformation,
};
use crate::versions::Version;

pub(crate) fn roster_list() -> Vec<Roster> {
    vec![
        Roster::Amazon,
        Roster::BlackOrc,
        Roster::ChaosChosen,
        Roster::ChaosDwarf,
        Roster::ChaosRenegade,
        Roster::DarkElf,
        Roster::Dwarf,
        Roster::ElvenUnion,
        Roster::Gnome,
        Roster::Goblin,
        Roster::Halfling,
        Roster::HighElf,
        Roster::Human,
        Roster::ImperialNobility,
        Roster::Khorne,
        Roster::Lizardmen,
        Roster::NecromanticHorror,
        Roster::Norse,
        Roster::Nurgle,
        Roster::Ogre,
        Roster::OldWorldAlliance,
        Roster::Orc,
        Roster::ShamblingUndead,
        Roster::Skaven,
        Roster::Snotling,
        Roster::TombKings,
        Roster::UnderworldDenizens,
        Roster::Vampire,
        Roster::WoodElf,
    ]
}

pub(crate) fn roster_definition_from(roster: &Roster) -> Option<RosterDefinition> {
    match roster {
        Roster::Amazon => Some(RosterDefinition {
            version: Version::V5,
            tier: 1,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_60,
            ],
            positions: vec![
                Position::EagleWarriorLinewoman,
                Position::PythonWarriorThrower,
                Position::PiranhaWarriorBlitzer,
                Position::JaguarWarriorBlocker,
            ],
            journeyman_position: Position::EagleWarriorLinewoman,
            maximum_big_men_quantity: 0,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::LustrianSuperleague],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::BlackOrc => Some(RosterDefinition {
            version: Version::V5,
            tier: 2,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_60,
            ],
            positions: vec![
                Position::GoblinBruiserLineman,
                Position::BlackOrc,
                Position::TrainedTroll,
            ],
            journeyman_position: Position::GoblinBruiserLineman,
            maximum_big_men_quantity: 1,
            special_leagues: Vec::new(),
            special_rules: vec![
                SpecialRule::BadlandsBrawl,
                SpecialRule::BriberyAndCorruption,
            ],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::ChaosChosen => Some(RosterDefinition {
            version: Version::V5,
            tier: 2,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_60,
            ],
            positions: vec![
                Position::BeastmanRunnerLineman,
                Position::ChosenBlocker,
                Position::ChaosTroll,
                Position::ChaosOgre,
                Position::Minotaur,
            ],
            journeyman_position: Position::BeastmanRunnerLineman,
            maximum_big_men_quantity: 1,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::FavouredOf],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::ChaosDwarf => Some(RosterDefinition {
            version: Version::V5,
            tier: 1,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_70,
            ],
            positions: vec![
                Position::HobgoblinLineman,
                Position::HobgoblinSneakyStabba,
                Position::ChaosDwarfBlocker,
                Position::ChaosDwarfFlamesmith,
                Position::BullCentaurBlitzer,
                Position::Minotaur,
            ],
            journeyman_position: Position::HobgoblinLineman,
            maximum_big_men_quantity: 1,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::BadlandsBrawl, SpecialRule::FavouredOfHashut],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::DarkElf => Some(RosterDefinition {
            version: Version::V5,
            tier: 1,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_50,
            ],
            positions: vec![
                Position::DarkElfLineman,
                Position::Runner,
                Position::Blitzer,
                Position::Assassin,
                Position::WitchElf,
            ],
            journeyman_position: Position::DarkElfLineman,
            maximum_big_men_quantity: 0,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::ElvenKingdomsLeague],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::Dwarf => Some(RosterDefinition {
            version: Version::V5,
            tier: 1,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_50,
            ],
            positions: vec![
                Position::DwarfBlockerLineman,
                Position::Runner,
                Position::Blitzer,
                Position::TrollSlayer,
                Position::Deathroller,
            ],
            journeyman_position: Position::DwarfBlockerLineman,
            maximum_big_men_quantity: 1,
            special_leagues: Vec::new(),
            special_rules: vec![
                SpecialRule::WorldsEdgeSuperleague,
                SpecialRule::OldWorldClassic,
            ],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::Gnome => Some(RosterDefinition {
            version: Version::V5,
            tier: 3,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_50,
            ],
            positions: vec![
                Position::GnomeLineman,
                Position::GnomeBeastmaster,
                Position::GnomeIllusionist,
                Position::WoodlandFox,
                Position::AlternForestTreeman,
            ],
            journeyman_position: Position::GnomeLineman,
            maximum_big_men_quantity: 2,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::HalflingThimbleCup],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::HighElf => Some(RosterDefinition {
            version: Version::V5,
            tier: 1,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_50,
            ],
            positions: vec![
                Position::Lineman,
                Position::Catcher,
                Position::Thrower,
                Position::Blitzer,
            ],
            journeyman_position: Position::Lineman,
            maximum_big_men_quantity: 0,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::ElvenKingdomsLeague],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::Human => Some(RosterDefinition {
            version: Version::V5,
            tier: 2,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_50,
            ],
            positions: vec![
                Position::HumanLineman,
                Position::Thrower,
                Position::Catcher,
                Position::Blitzer,
                Position::HalflingHopeful,
                Position::Ogre,
            ],
            journeyman_position: Position::HumanLineman,
            maximum_big_men_quantity: 1,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::OldWorldClassic],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::Lizardmen => Some(RosterDefinition {
            version: Version::V5,
            tier: 1,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_70,
            ],
            positions: vec![
                Position::SkinkRunnerLineman,
                Position::ChameleonSkink,
                Position::SaurusBlocker,
                Position::Kroxigor,
            ],
            journeyman_position: Position::SkinkRunnerLineman,
            maximum_big_men_quantity: 1,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::LustrianSuperleague],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::NecromanticHorror => Some(RosterDefinition {
            version: Version::V5,
            tier: 2,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::REROLL_70,
            ],
            positions: vec![
                Position::ZombieLineman,
                Position::GhoulRunner,
                Position::Wraith,
                Position::Werewolf,
                Position::FleshGolem,
            ],
            journeyman_position: Position::ZombieLineman,
            maximum_big_men_quantity: 0,
            special_leagues: Vec::new(),
            special_rules: vec![
                SpecialRule::SylvanianSpotlight,
                SpecialRule::MastersOfUndeath,
            ],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::Norse => Some(RosterDefinition {
            version: Version::V5,
            tier: 1,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_60,
            ],
            positions: vec![
                Position::NorseRaiderLineman,
                Position::BeerBoar,
                Position::NorseBerzerker,
                Position::Valkyrie,
                Position::Ulfwerener,
                Position::Yhetee,
            ],
            journeyman_position: Position::NorseRaiderLineman,
            maximum_big_men_quantity: 1,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::OldWorldClassic, SpecialRule::FavouredOf],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::Orc => Some(RosterDefinition {
            version: Version::V5,
            tier: 2,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_60,
            ],
            positions: vec![
                Position::OrcLineman,
                Position::Thrower,
                Position::Blitzer,
                Position::BigUn,
                Position::Goblin,
                Position::UntrainedTroll,
            ],
            journeyman_position: Position::OrcLineman,
            maximum_big_men_quantity: 1,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::BadlandsBrawl],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::Snotling => Some(RosterDefinition {
            version: Version::V5,
            tier: 3,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_60,
            ],
            positions: vec![
                Position::SnotlingLineman,
                Position::FungusFlinga,
                Position::FunHoppa,
                Position::StiltyRunna,
                Position::PumpWagon,
                Position::TrainedTroll,
            ],
            journeyman_position: Position::SnotlingLineman,
            maximum_big_men_quantity: 4,
            special_leagues: Vec::new(),
            special_rules: vec![
                SpecialRule::BriberyAndCorruption,
                SpecialRule::UnderworldChallenge,
                SpecialRule::LowCostLinemen,
            ],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        Roster::WoodElf => Some(RosterDefinition {
            version: Version::V5,
            tier: 1,
            staff_information: vec![
                StaffInformation::CHEERLEADER,
                StaffInformation::ASSISTANT,
                StaffInformation::APOTHECARY,
                StaffInformation::REROLL_50,
            ],
            positions: vec![
                Position::WoodElfLineman,
                Position::Thrower,
                Position::Catcher,
                Position::Wardancer,
                Position::LorenForestTreeman,
            ],
            journeyman_position: Position::WoodElfLineman,
            maximum_big_men_quantity: 1,
            special_leagues: Vec::new(),
            special_rules: vec![SpecialRule::ElvenKingdomsLeague],
            dedicated_fans_information: DedicatedFansInformation::DEFAULT,
        }),

        _ => None,
    }
}
