use crate::translation::{LOCALES, language_from};
use fluent_templates::Loader;
use std::borrow::Cow;
use std::collections::HashMap;

#[derive(Debug, Copy, Clone)]
pub enum SkillCategory {
    Agility,
    General,
    Mutation,
    Pass,
    Strength,
    Trait,
}

impl SkillCategory {
    pub fn short_name(self, lang_id: &str) -> String {
        match self {
            SkillCategory::Agility => LOCALES.lookup(&language_from(lang_id), "Agility-short"),
            SkillCategory::General => LOCALES.lookup(&language_from(lang_id), "General-short"),
            SkillCategory::Mutation => LOCALES.lookup(&language_from(lang_id), "Mutation-short"),
            SkillCategory::Pass => LOCALES.lookup(&language_from(lang_id), "Pass-short"),
            SkillCategory::Strength => LOCALES.lookup(&language_from(lang_id), "Strength-short"),
            SkillCategory::Trait => LOCALES.lookup(&language_from(lang_id), "Trait-short"),
        }
    }
}

#[derive(Debug, Copy, Clone)]
pub enum Skill {
    // General
    Block,
    Dauntless,
    DirtyPlayer(u8),
    Fend,
    Frenzy,
    Kick,
    Pro,
    Shadowing,
    StripBall,
    SureHands,
    Tackle,
    Wrestle,

    // Agility
    Catch,
    Defensive,
    DivingCatch,
    DivingTackle,
    Dodge,
    JumpUp,
    Leap,
    SideStep,
    SafePairOfHands,
    SneakyGit,
    Sprint,
    SureFeet,

    // Strength
    ArmBar,
    Brawler,
    BreakTackle,
    Grab,
    Guard,
    Juggernaut,
    MightyBlow(u8),
    MultipleBlock,
    PileDriver,
    StandFirm,
    StrongArm,
    ThickSkull,

    // Passing
    Accurate,
    Cannoneer,
    CloudBurster,
    DumpOff,
    Fumblerooskie,
    HailMaryPass,
    Leader,
    NervesOfSteel,
    OnTheBall,
    Pass,
    RunningPass,
    SafePass,

    // Mutation
    BigHand,
    Claw,
    DisturbingPresence,
    ExtraArms,
    FoulAppearance,
    Horns,
    IronHardSkin,
    MonstrousMouth,
    PrehensileTail,
    Tentacles,
    TwoHeads,
    VeryLongLegs,

    // Trait
    AlwaysHungry,
    Animosity,
    AnimalSavagery,
    BallChain,
    BloodLust,
    Bombardier,
    BoneHead,
    BreatheFire,
    Chainsaw,
    Decay,
    Drunkard,
    HitAndRun,
    HypnoticGaze,
    KickTeamMate,
    Loner(u8),
    MyBall,
    NoHands,
    PickMeUp,
    PlagueRidden,
    PogoStick,
    ProjectileVomit,
    ReallyStupid,
    Regeneration,
    RightStuff,
    SecretWeapon,
    Stab,
    Stunty,
    Swarming,
    Swoop,
    TakeRoots,
    Timmmber,
    Trickster,
    ThrowTeamMate,
    Titchy,
    UnchannelledFury,
}

impl Skill {
    pub fn name(self, lang_id: &str) -> String {
        match self {
            Skill::Block => LOCALES.lookup(&language_from(lang_id), "Block"),
            Skill::Dauntless => LOCALES.lookup(&language_from(lang_id), "Dauntless"),
            Skill::DirtyPlayer(value) => LOCALES.lookup_with_args(
                &language_from(lang_id),
                "DirtyPlayer",
                &HashMap::from([(Cow::from("value"), value.into())]),
            ),
            Skill::Fend => LOCALES.lookup(&language_from(lang_id), "Fend"),
            Skill::Frenzy => LOCALES.lookup(&language_from(lang_id), "Frenzy"),
            Skill::Kick => LOCALES.lookup(&language_from(lang_id), "Kick"),
            Skill::Pro => LOCALES.lookup(&language_from(lang_id), "Pro"),
            Skill::Shadowing => LOCALES.lookup(&language_from(lang_id), "Shadowing"),
            Skill::StripBall => LOCALES.lookup(&language_from(lang_id), "StripBall"),
            Skill::SureHands => LOCALES.lookup(&language_from(lang_id), "SureHands"),
            Skill::Tackle => LOCALES.lookup(&language_from(lang_id), "Tackle"),
            Skill::Wrestle => LOCALES.lookup(&language_from(lang_id), "Wrestle"),
            Skill::Catch => LOCALES.lookup(&language_from(lang_id), "Catch"),
            Skill::Defensive => LOCALES.lookup(&language_from(lang_id), "Defensive"),
            Skill::DivingCatch => LOCALES.lookup(&language_from(lang_id), "DivingCatch"),
            Skill::DivingTackle => LOCALES.lookup(&language_from(lang_id), "DivingTackle"),
            Skill::Dodge => LOCALES.lookup(&language_from(lang_id), "Dodge"),
            Skill::JumpUp => LOCALES.lookup(&language_from(lang_id), "JumpUp"),
            Skill::Leap => LOCALES.lookup(&language_from(lang_id), "Leap"),
            Skill::SideStep => LOCALES.lookup(&language_from(lang_id), "SideStep"),
            Skill::SafePairOfHands => LOCALES.lookup(&language_from(lang_id), "SafePairOfHands"),
            Skill::SneakyGit => LOCALES.lookup(&language_from(lang_id), "SneakyGit"),
            Skill::Sprint => LOCALES.lookup(&language_from(lang_id), "Sprint"),
            Skill::SureFeet => LOCALES.lookup(&language_from(lang_id), "SureFeet"),
            Skill::ArmBar => LOCALES.lookup(&language_from(lang_id), "ArmBar"),
            Skill::Brawler => LOCALES.lookup(&language_from(lang_id), "Brawler"),
            Skill::BreakTackle => LOCALES.lookup(&language_from(lang_id), "BreakTackle"),
            Skill::Grab => LOCALES.lookup(&language_from(lang_id), "Grab"),
            Skill::Guard => LOCALES.lookup(&language_from(lang_id), "Guard"),
            Skill::Juggernaut => LOCALES.lookup(&language_from(lang_id), "Juggernaut"),
            Skill::MightyBlow(value) => LOCALES.lookup_with_args(
                &language_from(lang_id),
                "MightyBlow",
                &HashMap::from([(Cow::from("value"), value.into())]),
            ),
            Skill::MultipleBlock => LOCALES.lookup(&language_from(lang_id), "MultipleBlock"),
            Skill::PileDriver => LOCALES.lookup(&language_from(lang_id), "PileDriver"),
            Skill::StandFirm => LOCALES.lookup(&language_from(lang_id), "StandFirm"),
            Skill::StrongArm => LOCALES.lookup(&language_from(lang_id), "StrongArm"),
            Skill::ThickSkull => LOCALES.lookup(&language_from(lang_id), "ThickSkull"),
            Skill::Accurate => LOCALES.lookup(&language_from(lang_id), "Accurate"),
            Skill::Cannoneer => LOCALES.lookup(&language_from(lang_id), "Cannoneer"),
            Skill::CloudBurster => LOCALES.lookup(&language_from(lang_id), "CloudBurster"),
            Skill::DumpOff => LOCALES.lookup(&language_from(lang_id), "DumpOff"),
            Skill::Fumblerooskie => LOCALES.lookup(&language_from(lang_id), "Fumblerooskie"),
            Skill::HailMaryPass => LOCALES.lookup(&language_from(lang_id), "HailMaryPass"),
            Skill::Leader => LOCALES.lookup(&language_from(lang_id), "Leader"),
            Skill::NervesOfSteel => LOCALES.lookup(&language_from(lang_id), "NervesOfSteel"),
            Skill::OnTheBall => LOCALES.lookup(&language_from(lang_id), "OnTheBall"),
            Skill::Pass => LOCALES.lookup(&language_from(lang_id), "Pass"),
            Skill::RunningPass => LOCALES.lookup(&language_from(lang_id), "RunningPass"),
            Skill::SafePass => LOCALES.lookup(&language_from(lang_id), "SafePass"),
            Skill::BigHand => LOCALES.lookup(&language_from(lang_id), "BigHand"),
            Skill::Claw => LOCALES.lookup(&language_from(lang_id), "Claw"),
            Skill::DisturbingPresence => {
                LOCALES.lookup(&language_from(lang_id), "DisturbingPresence")
            }
            Skill::ExtraArms => LOCALES.lookup(&language_from(lang_id), "ExtraArms"),
            Skill::FoulAppearance => LOCALES.lookup(&language_from(lang_id), "FoulAppearance"),
            Skill::Horns => LOCALES.lookup(&language_from(lang_id), "Horns"),
            Skill::IronHardSkin => LOCALES.lookup(&language_from(lang_id), "IronHardSkin"),
            Skill::MonstrousMouth => LOCALES.lookup(&language_from(lang_id), "MonstrousMouth"),
            Skill::PrehensileTail => LOCALES.lookup(&language_from(lang_id), "PrehensileTail"),
            Skill::Tentacles => LOCALES.lookup(&language_from(lang_id), "Tentacles"),
            Skill::TwoHeads => LOCALES.lookup(&language_from(lang_id), "TwoHeads"),
            Skill::VeryLongLegs => LOCALES.lookup(&language_from(lang_id), "VeryLongLegs"),
            Skill::AlwaysHungry => LOCALES.lookup(&language_from(lang_id), "AlwaysHungry"),
            Skill::Animosity => LOCALES.lookup(&language_from(lang_id), "Animosity"),
            Skill::AnimalSavagery => LOCALES.lookup(&language_from(lang_id), "AnimalSavagery"),
            Skill::BallChain => LOCALES.lookup(&language_from(lang_id), "BallChain"),
            Skill::BloodLust => LOCALES.lookup(&language_from(lang_id), "BloodLust"),
            Skill::Bombardier => LOCALES.lookup(&language_from(lang_id), "Bombardier"),
            Skill::BoneHead => LOCALES.lookup(&language_from(lang_id), "BoneHead"),
            Skill::BreatheFire => LOCALES.lookup(&language_from(lang_id), "BreatheFire"),
            Skill::Chainsaw => LOCALES.lookup(&language_from(lang_id), "Chainsaw"),
            Skill::Decay => LOCALES.lookup(&language_from(lang_id), "Decay"),
            Skill::Drunkard => LOCALES.lookup(&language_from(lang_id), "Drunkard"),
            Skill::HitAndRun => LOCALES.lookup(&language_from(lang_id), "HitAndRun"),
            Skill::HypnoticGaze => LOCALES.lookup(&language_from(lang_id), "HypnoticGaze"),
            Skill::KickTeamMate => LOCALES.lookup(&language_from(lang_id), "KickTeamMate"),
            Skill::Loner(value) => LOCALES.lookup_with_args(
                &language_from(lang_id),
                "Loner",
                &HashMap::from([(Cow::from("value"), value.into())]),
            ),
            Skill::MyBall => LOCALES.lookup(&language_from(lang_id), "MyBall"),
            Skill::NoHands => LOCALES.lookup(&language_from(lang_id), "NoHands"),
            Skill::PickMeUp => LOCALES.lookup(&language_from(lang_id), "PickMeUp"),
            Skill::PlagueRidden => LOCALES.lookup(&language_from(lang_id), "PlagueRidden"),
            Skill::PogoStick => LOCALES.lookup(&language_from(lang_id), "PogoStick"),
            Skill::ProjectileVomit => LOCALES.lookup(&language_from(lang_id), "ProjectileVomit"),
            Skill::ReallyStupid => LOCALES.lookup(&language_from(lang_id), "ReallyStupid"),
            Skill::Regeneration => LOCALES.lookup(&language_from(lang_id), "Regeneration"),
            Skill::RightStuff => LOCALES.lookup(&language_from(lang_id), "RightStuff"),
            Skill::SecretWeapon => LOCALES.lookup(&language_from(lang_id), "SecretWeapon"),
            Skill::Stab => LOCALES.lookup(&language_from(lang_id), "Stab"),
            Skill::Stunty => LOCALES.lookup(&language_from(lang_id), "Stunty"),
            Skill::Swarming => LOCALES.lookup(&language_from(lang_id), "Swarming"),
            Skill::Swoop => LOCALES.lookup(&language_from(lang_id), "Swoop"),
            Skill::TakeRoots => LOCALES.lookup(&language_from(lang_id), "TakeRoots"),
            Skill::Timmmber => LOCALES.lookup(&language_from(lang_id), "Timmmber"),
            Skill::Trickster => LOCALES.lookup(&language_from(lang_id), "Trickster"),
            Skill::ThrowTeamMate => LOCALES.lookup(&language_from(lang_id), "ThrowTeamMate"),
            Skill::Titchy => LOCALES.lookup(&language_from(lang_id), "Titchy"),
            Skill::UnchannelledFury => LOCALES.lookup(&language_from(lang_id), "UnchannelledFury"),
        }
    }
}
